export default [
    {
        market_id:'1324',
        name:'OKEx'
    },
    {
        market_id:'338',
        name:'币安'
    },
    {
        market_id:'108',
        name:'火币'
    },
    {
        market_id:'1333',
        name:'Gate.io'
    },
    {
        market_id:'1352',
        name:'BigONE'
    },
    {
        market_id:'1376',
        name:'币赢'
    },
    {
        market_id:'6',
        name:'Bittrex'
    },
    {
        market_id:'34',
        name:'以德'
    }
];